version: '3.5'
services:
    {{cookiecutter.repo_name}}:
        image: {{cookiecutter.dockerhub_org}}/{{cookiecutter.repo_name}}
        container_name: {{cookiecutter.repo_name}}
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE={{cookiecutter.mysql_database}}
            - CORS_ALLOWED_ORIGINS=*
            - MODE=DEV
        ports:
            - 8181:8000
        restart: always
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
volumes:
    mysql-data:
networks:
    my-app:
        name: my-app
        driver: bridge